---
title: Toon een bericht op de Sense HAT
hero_image: images/banner.png
description: Leer hoe je een scrollend bericht kunt weergeven op de LED-matrix van de Sense HAT
theme: red #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "sense-hat, python"
steps:
  - title: Inleiding
